name: metamorphosis
version: '0.2'
base: core18
summary: A daemon that exports metrics from kafka to influx.
description: A daemon that exports metrics from kafka to influx.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  metamorphosis:
    command: exporter-wrapper.bash
    daemon: simple
    plugs:
    - network
    - network-bind

parts:
  metamorphosis:
    plugin: go
    source: .
    go-importpath: github.com/cloud-green/metamorphosis
    build-packages:
    - git
    - gcc
  wrapper:
    plugin: dump
    source: snap/local
